started adding some functions

diff --git a/bin/deployarmpkg b/bin/deployarmpkg
--- a/bin/deployarmpkg
+++ b/bin/deployarmpkg
@@ -1,76 +1,57 @@
 #! /bin/bash
 
-# Usage: deployarmpkg package architecture repo
-# Example: deployarmpkg filesystem-2018.06-2-armv7h.pkg.tar.xz armv7h core
 
-#Display messages
- msg() {
-    ALL_OFF="\e[1;0m"
-    BOLD="\e[1;1m"
-    GREEN="${BOLD}\e[1;32m"
-      local mesg=$1; shift
-      printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
- }
- 
-  usage='Syntax: deployarmpkg -p package -a architecture -r repo
- Example: deployarmpkg -p filesystem-2018.07-1-armv7h.pkg.tar.xz -a armv7h -p core'
- 
-# if [[ -z "$1" ]]; then
-# echo "$usage"
-# elif [[ -z "$2" ]]; then
-# echo "$usage"
-# elif [[ -z "$3" ]]; then
-# echo "$usage"
-# else
 
 # Set globals
-SERVER='sync.manjaro-arm.org'
 _LIBDIR=/usr/share/manjaro-arm-tools/lib
 
-opt_vars=":p:a:r:"
+source $_LIBDIR/functions.sh
 
-while getopts "$opt_vars" arg; do
+opt=":p:a:r:h"
+
+while getopts "${opt}" arg; do
   case $arg in
     p)
-      package="$OPTARG" >&2
+      package="${OPTARG%/}"
       ;;
     a)
-      arch="$OPTARG" >&2
+      arch="${OPTARG}"
       ;;
     r)
-      repo="$OPTARG" >&2
+      repo="${OPTARG}"
     \?)
-      echo "Invalid option: -$OPTARG" >&2
+      echo "Invalid option: -${OPTARG}"
       exit 1
       ;;
     h|?)
-      echo $usage
+      usage_deploy_package
+      exit 1
       ;;
     :)
-      echo "Option -$OPTARG requires an argument." >&2
+      echo "Option -${OPTARG} requires an argument."
       exit 1
       ;;
   esac
 done
 
+if [ "x" == "x$package" ]; then
+  echo "-p [option] is required"
+  exit
+fi
+if [ "x" == "x$arch" ]; then
+  echo "-a [option] is required"
+  exit
+fi
+if [ "x" == "x$repo" ]; then
+  echo "-r [option] is required"
+  exit
+fi
+
 # Sign the package with the users gpg key
-msg "Signing [$package] with users GPG key..."
-gpg --detach-sign "$package"
+sign_pkg
 
 # Upload pkg + signature to repo server
-msg "Uploading package to server..."
-echo "Please use your server login details..."
-scp $package* $SERVER:/opt/repo/mirror/stable/$arch/$repo/
-
-# Adding package to repo
-msg "Adding [$package] to repo..."
-echo "Please use your server login details..."
-#ssh -T $SERVER sudo systemd-nspawn -D /opt/repo/ repo-add -q -n -R /mirror/stable/$arch/$repo/$repo.db.tar.gz /mirror/stable/$arch/$repo/$package
-#Not sure if this bit works yet
-ssh $SERVER 'bash -s' < $_LIBDIR/repo-add.sh "$@"
+pkg_upload
 
 # remove pkg + sig from cache folder
-msg "Removing local files..."
-rm $package*
-
-fi
+remove_local_files
